#!/bin/bash

toHEVCfunc () {
   echo "${0} is converting all ${1} files in $(pwd) to HEVC recursively"
   for file in ./*."${1}"; do
      if [ "${file}" = "./*.${1}" ] ; then
         echo "empty folder!"
         continue
      fi
      ffmpeg -i "${file}" 2>&1 | grep "Video: hevc"
      if [ $? = 0 ] ; then
         echo "${file} is already of HEVC codec"
         continue
      fi
      echo "Converting ${file} ..."
      ffmpeg -i "${file}" -c:v libx265 -crf 21 -c:a aac -f mp4 \
      -pix_fmt yuv420p -tag:v hvc1 -movflags faststart output.mp4
      if [ $? = 255 ] ; then
         return 255
      elif ! [ $? = 0 ] ; then
         rm output.mp4
         continue
      fi
      echo "Cleaning up ..."
      mv output.mp4 "${file}"
   done
   for folder in *; do
      if [ -d "${folder}" ]; then
         echo "Opening ${folder} ..."
      else
         echo "Skipping file ${folder}"
         continue;
      fi
      if [ "${folder}" = "." ] || [ "${folder}" = ".." ] || \
      [ "${folder}" = "*" ]
      then
         echo "Skipping current or parent directory"
      continue
      fi
      cd "${folder}" 
      toHEVCfunc $@
      if [ $? = 255 ] ; then
         return 255
      fi
      cd ..
   done
}

toHEVCfunc $@

